### PR TITLE
Support PHP 8.0

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Comment by Yozhef** [comment]
@theofidry maybe move Travis to Git Hub Actions? Now Travis build did not work.

**Comment by theofidry** [comment]
I'll welcome a switch but I can't work on it myself at the moment; that said a PHP8 build is likely to not be working due to requiring Composer 2 which is blocked by https://github.com/wikimedia/composer-merge-plugin/pull/189

**Comment by VincentLanglet** [comment]
> I'll welcome a switch but I can't work on it myself at the moment; that said a PHP8 build is likely to not be working due to requiring Composer 2 which is blocked by [wikimedia/composer-merge-plugin#189](https://github.com/wikimedia/composer-merge-plugin/pull/189)

Why composer 2 is required ? Can't the tests run with composer 1 ?

**Comment by alexislefebvre** [comment]
You can use `composer self-update --1` to keep using Composer 1 until issues are solved.

**Comment by theofidry** [comment]
>Why composer 2 is required ? Can't the tests run with composer 1 ?

Right actually if Composer 1 works with PHP8 there is no issue

**Comment by VincentLanglet** [comment]
> > Why composer 2 is required ? Can't the tests run with composer 1 ?
> 
> Right actually if Composer 1 works with PHP8 there is no issue

https://github.com/composer/composer/blob/1.10/composer.json#L25

**Comment by alexislefebvre** [comment]
@Yozhef we'll have to use Composer 1 for now, please try to add `composer self-update --1` before running the tests.

Adding

```
before_script:
  - composer self-update --1
```

before `script: make` in `.travis.yml` should fix the issue hopefully.

**Comment by Yozhef** [comment]
@alexislefebvre Today I want to implement GitHub Actions here too - and will I change it well there?

**Comment by alexislefebvre** [comment]
I suggest you to try to use Travis CI with this change, and switch to GitHub Actions if it doesn't work. If it works, we could switch to GA later in another PR.

**Comment by Yozhef** [comment]
@alexislefebvre Okey.
In This PR  ready move to GitHub Actions:
https://github.com/theofidry/composer-inheritance-plugin/pull/9
But have 1 point in php version 7.1 7.2 - it is not clear what the problem is but I watched the don already live quite a long time

**Comment by alexislefebvre** [comment]
It looks like Travis CI didn't run the tests.

**Comment by theofidry** [comment]
#9 merged; if it's of any help I'm fine with dropping support for anything bellow 7.3

**Comment by Yozhef** [comment]
@theofidry 
Failed 8.0 theofidry/composer-inheritance-plugin this is normal because the tests pull this package master version in which there is no support for PHP 8.0.

Faile - 7.1 and 7.2 - Maybe you'll tell me - I can downgrade the PHP version locally for debugging but a little later

**Review by alexislefebvre — APPROVED** [review]

**Comment by theofidry** [comment]
Alright let's see if it works! Thanks @Yozhef

**Comment by alexislefebvre** [comment]
Could you please publish a new release?

**Pull request merged**
